/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bns.hstcld.functions;

import com.bns.hstcld.functions.http.HelloWorld;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        HelloWorld classUnderTest = new HelloWorld();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
